/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLAirAbsorptionModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLAirAbsorptionModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLAirAbsorptionModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLAirAbsorptionModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLAirAbsorptionModelType value) {
    phononJNI.IPLAirAbsorptionModel_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLAirAbsorptionModelType getType() {
    return IPLAirAbsorptionModelType.swigToEnum(phononJNI.IPLAirAbsorptionModel_type_get(swigCPtr, this));
  }

  public void setCoefficients(float[] value) {
    phononJNI.IPLAirAbsorptionModel_coefficients_set(swigCPtr, this, value);
  }

  public float[] getCoefficients() {
    return phononJNI.IPLAirAbsorptionModel_coefficients_get(swigCPtr, this);
  }

  public void setCallback(SWIGTYPE_p_f_float_int_p_void__float value) {
    phononJNI.IPLAirAbsorptionModel_callback_set(swigCPtr, this, SWIGTYPE_p_f_float_int_p_void__float.getCPtr(value));
  }

  public SWIGTYPE_p_f_float_int_p_void__float getCallback() {
    long cPtr = phononJNI.IPLAirAbsorptionModel_callback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_float_int_p_void__float(cPtr, false);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    phononJNI.IPLAirAbsorptionModel_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = phononJNI.IPLAirAbsorptionModel_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDirty(boolean value) {
    phononJNI.IPLAirAbsorptionModel_dirty_set(swigCPtr, this, value);
  }

  public boolean getDirty() {
    return phononJNI.IPLAirAbsorptionModel_dirty_get(swigCPtr, this);
  }

  public IPLAirAbsorptionModel() {
    this(phononJNI.new_IPLAirAbsorptionModel(), true);
  }

}
