/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLAirAbsorptionModelType {
  IPL_AIRABSORPTION_DEFAULT,
  IPL_AIRABSORPTION_EXPONENTIAL,
  IPL_AIRABSORPTION_CALLBACK;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLAirAbsorptionModelType swigToEnum(int swigValue) {
    IPLAirAbsorptionModelType[] swigValues = IPLAirAbsorptionModelType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLAirAbsorptionModelType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLAirAbsorptionModelType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLAirAbsorptionModelType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLAirAbsorptionModelType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLAirAbsorptionModelType(IPLAirAbsorptionModelType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

