/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLBakedDataType {
  IPL_BAKEDDATATYPE_STATICSOURCE,
  IPL_BAKEDDATATYPE_STATICLISTENER,
  IPL_BAKEDDATATYPE_REVERB;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLBakedDataType swigToEnum(int swigValue) {
    IPLBakedDataType[] swigValues = IPLBakedDataType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLBakedDataType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLBakedDataType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLBakedDataType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLBakedDataType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLBakedDataType(IPLBakedDataType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

