/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLBakedDataIdentifier {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLBakedDataIdentifier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLBakedDataIdentifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLBakedDataIdentifier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdentifier(int value) {
    phononJNI.IPLBakedDataIdentifier_identifier_set(swigCPtr, this, value);
  }

  public int getIdentifier() {
    return phononJNI.IPLBakedDataIdentifier_identifier_get(swigCPtr, this);
  }

  public void setType(IPLBakedDataType value) {
    phononJNI.IPLBakedDataIdentifier_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLBakedDataType getType() {
    return IPLBakedDataType.swigToEnum(phononJNI.IPLBakedDataIdentifier_type_get(swigCPtr, this));
  }

  public IPLBakedDataIdentifier() {
    this(phononJNI.new_IPLBakedDataIdentifier(), true);
  }

}
