/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLBox {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLBox(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLBox obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLBox(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMinCoordinates(IPLVector3 value) {
    phononJNI.IPLBox_minCoordinates_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getMinCoordinates() {
    long cPtr = phononJNI.IPLBox_minCoordinates_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setMaxCoordinates(IPLVector3 value) {
    phononJNI.IPLBox_maxCoordinates_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getMaxCoordinates() {
    long cPtr = phononJNI.IPLBox_maxCoordinates_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public IPLBox() {
    this(phononJNI.new_IPLBox(), true);
  }

}
