/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLBakingSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLBakingSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLBakingSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLBakingSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBakeParametric(boolean value) {
    phononJNI.IPLBakingSettings_bakeParametric_set(swigCPtr, this, value);
  }

  public boolean getBakeParametric() {
    return phononJNI.IPLBakingSettings_bakeParametric_get(swigCPtr, this);
  }

  public void setBakeConvolution(boolean value) {
    phononJNI.IPLBakingSettings_bakeConvolution_set(swigCPtr, this, value);
  }

  public boolean getBakeConvolution() {
    return phononJNI.IPLBakingSettings_bakeConvolution_get(swigCPtr, this);
  }

  public void setIrDurationForBake(float value) {
    phononJNI.IPLBakingSettings_irDurationForBake_set(swigCPtr, this, value);
  }

  public float getIrDurationForBake() {
    return phononJNI.IPLBakingSettings_irDurationForBake_get(swigCPtr, this);
  }

  public IPLBakingSettings() {
    this(phononJNI.new_IPLBakingSettings(), true);
  }

}
