/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLChannelOrder {
  IPL_CHANNELORDER_INTERLEAVED,
  IPL_CHANNELORDER_DEINTERLEAVED;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLChannelOrder swigToEnum(int swigValue) {
    IPLChannelOrder[] swigValues = IPLChannelOrder.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLChannelOrder swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLChannelOrder.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLChannelOrder() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLChannelOrder(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLChannelOrder(IPLChannelOrder swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

