/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLComputeDeviceType {
  IPL_COMPUTEDEVICE_CPU,
  IPL_COMPUTEDEVICE_GPU,
  IPL_COMPUTEDEVICE_ANY;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLComputeDeviceType swigToEnum(int swigValue) {
    IPLComputeDeviceType[] swigValues = IPLComputeDeviceType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLComputeDeviceType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLComputeDeviceType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLComputeDeviceType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLComputeDeviceType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLComputeDeviceType(IPLComputeDeviceType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

