/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLComputeDeviceFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLComputeDeviceFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLComputeDeviceFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLComputeDeviceFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLComputeDeviceType value) {
    phononJNI.IPLComputeDeviceFilter_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLComputeDeviceType getType() {
    return IPLComputeDeviceType.swigToEnum(phononJNI.IPLComputeDeviceFilter_type_get(swigCPtr, this));
  }

  public void setMaxCUsToReserve(int value) {
    phononJNI.IPLComputeDeviceFilter_maxCUsToReserve_set(swigCPtr, this, value);
  }

  public int getMaxCUsToReserve() {
    return phononJNI.IPLComputeDeviceFilter_maxCUsToReserve_get(swigCPtr, this);
  }

  public void setFractionCUsForIRUpdate(float value) {
    phononJNI.IPLComputeDeviceFilter_fractionCUsForIRUpdate_set(swigCPtr, this, value);
  }

  public float getFractionCUsForIRUpdate() {
    return phononJNI.IPLComputeDeviceFilter_fractionCUsForIRUpdate_get(swigCPtr, this);
  }

  public IPLComputeDeviceFilter() {
    this(phononJNI.new_IPLComputeDeviceFilter(), true);
  }

}
