/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLConvolutionType {
  IPL_CONVOLUTIONTYPE_PHONON,
  IPL_CONVOLUTIONTYPE_TRUEAUDIONEXT;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLConvolutionType swigToEnum(int swigValue) {
    IPLConvolutionType[] swigValues = IPLConvolutionType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLConvolutionType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLConvolutionType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLConvolutionType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLConvolutionType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLConvolutionType(IPLConvolutionType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

