/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLDistanceAttenuationModelType {
  IPL_DISTANCEATTENUATION_DEFAULT,
  IPL_DISTANCEATTENUATION_INVERSEDISTANCE,
  IPL_DISTANCEATTENUATION_CALLBACK;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLDistanceAttenuationModelType swigToEnum(int swigValue) {
    IPLDistanceAttenuationModelType[] swigValues = IPLDistanceAttenuationModelType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLDistanceAttenuationModelType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLDistanceAttenuationModelType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLDistanceAttenuationModelType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLDistanceAttenuationModelType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLDistanceAttenuationModelType(IPLDistanceAttenuationModelType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

