/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLDistanceAttenuationModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLDistanceAttenuationModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLDistanceAttenuationModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLDistanceAttenuationModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLDistanceAttenuationModelType value) {
    phononJNI.IPLDistanceAttenuationModel_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLDistanceAttenuationModelType getType() {
    return IPLDistanceAttenuationModelType.swigToEnum(phononJNI.IPLDistanceAttenuationModel_type_get(swigCPtr, this));
  }

  public void setMinDistance(float value) {
    phononJNI.IPLDistanceAttenuationModel_minDistance_set(swigCPtr, this, value);
  }

  public float getMinDistance() {
    return phononJNI.IPLDistanceAttenuationModel_minDistance_get(swigCPtr, this);
  }

  public void setCallback(SWIGTYPE_p_f_float_p_void__float value) {
    phononJNI.IPLDistanceAttenuationModel_callback_set(swigCPtr, this, SWIGTYPE_p_f_float_p_void__float.getCPtr(value));
  }

  public SWIGTYPE_p_f_float_p_void__float getCallback() {
    long cPtr = phononJNI.IPLDistanceAttenuationModel_callback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_float_p_void__float(cPtr, false);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    phononJNI.IPLDistanceAttenuationModel_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = phononJNI.IPLDistanceAttenuationModel_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDirty(boolean value) {
    phononJNI.IPLDistanceAttenuationModel_dirty_set(swigCPtr, this, value);
  }

  public boolean getDirty() {
    return phononJNI.IPLDistanceAttenuationModel_dirty_get(swigCPtr, this);
  }

  public IPLDistanceAttenuationModel() {
    this(phononJNI.new_IPLDistanceAttenuationModel(), true);
  }

}
