/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLDirectOcclusionMode {
  IPL_DIRECTOCCLUSION_NONE,
  IPL_DIRECTOCCLUSION_NOTRANSMISSION,
  IPL_DIRECTOCCLUSION_TRANSMISSIONBYVOLUME,
  IPL_DIRECTOCCLUSION_TRANSMISSIONBYFREQUENCY;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLDirectOcclusionMode swigToEnum(int swigValue) {
    IPLDirectOcclusionMode[] swigValues = IPLDirectOcclusionMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLDirectOcclusionMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLDirectOcclusionMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLDirectOcclusionMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLDirectOcclusionMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLDirectOcclusionMode(IPLDirectOcclusionMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

