/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLHrtfParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLHrtfParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLHrtfParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLHrtfParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLHrtfDatabaseType value) {
    phononJNI.IPLHrtfParams_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLHrtfDatabaseType getType() {
    return IPLHrtfDatabaseType.swigToEnum(phononJNI.IPLHrtfParams_type_get(swigCPtr, this));
  }

  public void setHrtfData(SWIGTYPE_p_unsigned_char value) {
    phononJNI.IPLHrtfParams_hrtfData_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getHrtfData() {
    long cPtr = phononJNI.IPLHrtfParams_hrtfData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSofaFileName(String value) {
    phononJNI.IPLHrtfParams_sofaFileName_set(swigCPtr, this, value);
  }

  public String getSofaFileName() {
    return phononJNI.IPLHrtfParams_sofaFileName_get(swigCPtr, this);
  }

  public IPLHrtfParams() {
    this(phononJNI.new_IPLHrtfParams(), true);
  }

}
