/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLHrtfDatabaseType {
  IPL_HRTFDATABASETYPE_DEFAULT,
  IPL_HRTFDATABASETYPE_SOFA;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLHrtfDatabaseType swigToEnum(int swigValue) {
    IPLHrtfDatabaseType[] swigValues = IPLHrtfDatabaseType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLHrtfDatabaseType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLHrtfDatabaseType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLHrtfDatabaseType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLHrtfDatabaseType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLHrtfDatabaseType(IPLHrtfDatabaseType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

