/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLHrtfInterpolation {
  IPL_HRTFINTERPOLATION_NEAREST,
  IPL_HRTFINTERPOLATION_BILINEAR;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLHrtfInterpolation swigToEnum(int swigValue) {
    IPLHrtfInterpolation[] swigValues = IPLHrtfInterpolation.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLHrtfInterpolation swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLHrtfInterpolation.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLHrtfInterpolation() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLHrtfInterpolation(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLHrtfInterpolation(IPLHrtfInterpolation swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

