/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLProbePlacement {
  IPL_PLACEMENT_CENTROID,
  IPL_PLACEMENT_OCTREE,
  IPL_PLACEMENT_UNIFORMFLOOR;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLProbePlacement swigToEnum(int swigValue) {
    IPLProbePlacement[] swigValues = IPLProbePlacement.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLProbePlacement swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLProbePlacement.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLProbePlacement() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLProbePlacement(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLProbePlacement(IPLProbePlacement swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

