/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLSimulationType {
  IPL_SIMTYPE_REALTIME,
  IPL_SIMTYPE_BAKED;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLSimulationType swigToEnum(int swigValue) {
    IPLSimulationType[] swigValues = IPLSimulationType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLSimulationType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLSimulationType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLSimulationType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLSimulationType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLSimulationType(IPLSimulationType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

