/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public enum IPLSceneType {
  IPL_SCENETYPE_PHONON,
  IPL_SCENETYPE_EMBREE,
  IPL_SCENETYPE_RADEONRAYS,
  IPL_SCENETYPE_CUSTOM;

  public final int swigValue() {
    return swigValue;
  }

  public static IPLSceneType swigToEnum(int swigValue) {
    IPLSceneType[] swigValues = IPLSceneType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IPLSceneType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IPLSceneType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IPLSceneType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IPLSceneType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IPLSceneType(IPLSceneType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

