/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLSphere {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLSphere(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLSphere obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLSphere(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCenter(IPLVector3 value) {
    phononJNI.IPLSphere_center_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getCenter() {
    long cPtr = phononJNI.IPLSphere_center_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setRadius(float value) {
    phononJNI.IPLSphere_radius_set(swigCPtr, this, value);
  }

  public float getRadius() {
    return phononJNI.IPLSphere_radius_get(swigCPtr, this);
  }

  public IPLSphere() {
    this(phononJNI.new_IPLSphere(), true);
  }

}
