/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLTriangle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLTriangle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLTriangle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLTriangle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndices(int[] value) {
    phononJNI.IPLTriangle_indices_set(swigCPtr, this, value);
  }

  public int[] getIndices() {
    return phononJNI.IPLTriangle_indices_get(swigCPtr, this);
  }

  public IPLTriangle() {
    this(phononJNI.new_IPLTriangle(), true);
  }

}
