/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.valvesoftware.phonon;

public class IPLVector3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLVector3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLVector3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        phononJNI.delete_IPLVector3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    phononJNI.IPLVector3_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return phononJNI.IPLVector3_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    phononJNI.IPLVector3_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return phononJNI.IPLVector3_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    phononJNI.IPLVector3_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return phononJNI.IPLVector3_z_get(swigCPtr, this);
  }

  public IPLVector3() {
    this(phononJNI.new_IPLVector3(), true);
  }

}
